language: go

go:
  - 1.6
  - 1.5
  - tip

sudo: false

before_install:
  - export GO15VENDOREXPERIMENT=1

install:
  - echo 'nop'

script:
  - mkdir -p  $HOME/gopath/src/github.com/coreos/clair/
  - rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/coreos/clair/
  - cd $HOME/gopath/src/github.com/coreos/clair/
  - go test -v $(go list ./... | grep -v /vendor/)

services:
  - postgresql

addons:
  apt:
    packages:
      - rpm
  postgresql: "9.4"

notifications:
  email: false
